name: in_app_purchase_storekit
description: An implementation for the iOS and macOS platforms of the Flutter `in_app_purchase` plugin. This uses the StoreKit Framework.

version: 0.3.10

environment:
  sdk: ^3.2.3
  flutter: ">=3.16.6"

flutter:
  plugin:
    implements: in_app_purchase
    platforms:
      ios:
        pluginClass: InAppPurchasePlugin
        sharedDarwinSource: true
      macos:
        pluginClass: InAppPurchasePlugin
        sharedDarwinSource: true

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  in_app_purchase_platform_interface: ^1.3.0
  json_annotation: ^4.3.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  pigeon: ^16.0.4
  test: ^1.16.0

topics:
  - in-app-purchase
  - payment
